version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  basket.data:
    image: redis:alpine

  basket.api:
    image: ${DOCKER_REGISTRY}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    depends_on:
    - rabbitmq
    - basket.data

  identity.api:
    image: ${DOCKER_REGISTRY}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile
    depends_on:
    - sql.data


  ordering.api:
    image: ${DOCKER_REGISTRY}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile


  provider.api:
    image: ${DOCKER_REGISTRY}providerapi
    build:
      context: .
      dockerfile: Services/Provider/Provider.API/Dockerfile


  catalog.api:
    image: ${DOCKER_REGISTRY}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

