version: '3.4'

services:
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44312
      - EventBusConnection=rabbitmq
      - EventBusPassword=guest
      - EventBusUserName=guest
      - ConnectionString=basket.data
    ports:
      - "51361:80"
      - "44312:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
  
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"  

  basket.data:
    ports:
      - "15673:15673"
      - "5673:5673"