version: '3.4'

services:
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest

  nosql.data:
    image: mongo

  basket.data:
    image: redis:alpine
      
  rabbitmq:
    image: rabbitmq:3-management-alpine

  mervi:
    image: ${DOCKER_REGISTRY}mervi
    build:
      context: .  
      dockerfile: Mervi/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile


  provider.api:
    image: ${DOCKER_REGISTRY}providerapi
    build:
      context: .
      dockerfile: Services/Provider/Provider.API/Dockerfile


  basket.api:
    image: ${DOCKER_REGISTRY}basketapi
    build:
      context: .
      dockerfile: ../Basket.API/Dockerfile
    depends_on:
      - basket.data,
      - rabbitmq
